name: linklocker
description: "..."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #  launcher icon
  flutter_launcher_icons: ^0.14.2

  #  routing
  go_router: ^14.6.2

  #  to get file and folder path
  path: ^1.9.0
  path_provider: ^2.1.5

  #  local database
  sqflite: ^2.4.1

  #  data and time
  intl: ^0.20.1

  #  qr generator
  qr_flutter: ^4.1.0

  #  to generate pie chart
  fl_chart: ^0.70.1

  #  to pick image
  image_picker: ^1.1.2

  #  share text [links]
  share_plus: ^10.1.3

  #  call dialer
  url_launcher: ^6.3.1

  #  image compressor
  flutter_image_compress: ^2.4.0
  mobile_scanner: ^6.0.2

# launcher icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/ic_launcher.png'
  adaptive_icon_foreground: 'assets/icons/ic_launcher.png'
  adaptive_icon_background: '#000000'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: 'poppins'
      fonts:
        - asset: assets/fonts/poppins-regular.ttf

    - family: 'roboto'
      fonts:
        - asset: assets/fonts/roboto-regular.ttf

    - family: 'patrickhand'
      fonts:
        - asset: assets/fonts/patrickhand-regular.ttf