name: linklocker
description: "..."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  go_router: ^14.6.2
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  intl: ^0.20.1
  qr_flutter: ^4.1.0
  fl_chart: ^0.70.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_image_compress: ^2.4.0
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  share_plus: ^10.1.4
  remove: ^1.0.10
  mobile_scanner: ^6.0.7
  meta: ^1.16.0
  bloc: ^9.0.0
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.5

# launcher icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/ic_launcher.png'
  adaptive_icon_foreground: 'assets/icons/ic_launcher.png'
  adaptive_icon_background: '#000000'

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/icons/ic_launcher.png
  image_dark: assets/icons/ic_launcher.png
  fullscreen: true
  android: true
  ios: true

  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    image: assets/icons/ic_launcher.png
    image_dark: assets/icons/ic_launcher.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/

  fonts:
    - family: 'poppins'
      fonts:
        - asset: assets/fonts/poppins-regular.ttf

    - family: 'roboto'
      fonts:
        - asset: assets/fonts/roboto-regular.ttf

    - family: 'patrickhand'
      fonts:
        - asset: assets/fonts/patrickhand-regular.ttf